services:
  db:
    image: postgres:16
    container_name: postgres-container
    environment:
      POSTGRES_DB: db_backend_products
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db_backend_products
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456789
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend

volumes:
  pgdata:
