spring.application.name=backend-products
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://crud_db_5esx_user:eST45XRtw3HgHQw75NFLKJ50QW3dCLtd@dpg-d9kih9e417fc73bpal2g-a/crud_db_5esx}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456789}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

jwt.secret=${JWT_SECRET:TP3DS2pN5^Gq7L2*4pX!L9Y0S1EaP&0K&u8*!K22@3*%6oBRIB}
jwt.expiration=900000
# 15 minutos = 1000 * 60 * 15
jwt.refreshExpiration=604800000
#7 dias = 1000 * 60 * 60 * 24 * 7
