spring.application.name=backend-products
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/crud_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

jwt.secret=${JWT_SECRET:default_dev_secret_key_change_in_production}
jwt.expiration=900000
# 15 minutos = 1000 * 60 * 15
jwt.refreshExpiration=604800000
#7 dias = 1000 * 60 * 60 * 24 * 7
